DevOps with Docker description.
rage/old.mooc.fi pull request #1
Opened 2019-03-04 10:15 UTC by Jakousa

href and image missing. Are they required?

2019-03-04 10:29 UTC, nygrenh requested changes
Image is required.

Can you also put this to finnish upcoming courses so that the course gets more exposure? Most of our visitors are only looking at the finnish pages.

2019-03-04 21:39 UTC, Jakousa commented
Deployment was a hard translate. I tried to copy the wordings used in other descriptions. 
Image was under Creative Commons CC0 found from https://pxhere.com/en/photo/1193989.

2019-03-06 11:05 UTC, nygrenh approved these changes

2019-03-06 11:05 UTC, merged

2019-05-20 07:34 UTC, Ukonhattu commented
Sisältää uusimman toimivan version backendistä